name: Creación del release una vez se ejecutan las pruebas unitarias

on:
  push:
    # Sequence of patterns matched against refs/tags
     branches: [ develop ]

jobs:
  if_merged:
    name: Generación del release
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configuración de entorno de python
        uses: actions/setup-python@v2
        with:
            python-version: '3.7'


      - name: Instalación de librerías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Ejecutar pruebas
      - name: Ejecutar pruebas
        run: |
          python -m unittest tests/test_album.py
        continue-on-error: true
        id: test_result

      - name: Verificar resultado de las pruebas
        if: ${{ failure() }}
        run: |
          echo "Las pruebas unitarias fallaron, no se crea la rama release"
    
      #Crear un release
      - name: Crear Release
        if: steps.test_result.outcome == 'success'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          release_name: Release ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false